spring:
  datasource:
    url: jdbc:h2:mem:~/review-api;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    driver-class-name: org.h2.Driver
  application:
    name: review
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  instance:
    hostname: localhost
